---
title: "BAYESTA Multilevel Modelling"
output: html_notebook
---

```{r}
library(haven)
library(dplyr)
library(writexl)
library(readxl)
library(nlme)
library(rstanarm)
library(rstan)
library(brms)
library(lme4)
library(effects)
library(sjPlot)
library(mitml)

```

```{r}
setwd("C:/Users/albert go/Desktop/Schoolworks/BAYESTA/Project FIles")
qq_phl_merged <- read_excel("BayestatData.xlsx")

```


```{r}

qq_phl_merged_complete <- na.omit(qq_phl_merged)
qq_phl_merged_complete$CNTSCHID <- as.factor(qq_phl_merged_complete$CNTSCHID)
```

```{r}
#Traditional Multilevel Model
#Step 1 - Examine the Intraclass Correlation Coefficient in mixed-effect models (ICC(1)) of the outcome

#ICC(1)
Null.Model <- lme(PERFMATH ~ 1, random = ~1|CNTSCHID, data = qq_phl_merged_complete, control=list(opt="optim"))

VarCorr(Null.Model)
1806.535/(1806.535+3377.601)

Null.gls <- gls(PERFMATH ~1, data = qq_phl_merged_complete)
anova(Null.gls,Null.Model)

#There is significant intercept variation. 34.85% of the variation in PV1MATH scores is a function of the school
#where they belong. Thus, a model that allows for random variation in PV1MATH among schools is a better fit than a model that does not allow random variation
```
```{r}
#Step 2 - Explain Level 1 and Level 2 Intercept Variance
#Level 1 - ESCS, parent_support, gender
#Level 2 - student_hindrance, teacher_hindrance

Model.1a<-lme(PERFMATH~ESCS+parent_support+gender, random=~student_hindrance+teacher_hindrance|CNTSCHID,
              data=qq_phl_merged_complete,control=list(opt="optim"))

Model.1b<-lme(PERFMATH~ESCS+parent_support+gender+student_hindrance*ESCS+teacher_hindrance*ESCS ,random=~student_hindrance+teacher_hindrance|CNTSCHID,
             data=qq_phl_merged_complete,control=list(opt="optim"))

Model.1c<-lme(PERFMATH~ESCS+parent_support+gender+student_hindrance+teacher_hindrance,random=~student_hindrance+teacher_hindrance|CNTSCHID,
             data=qq_phl_merged_complete,control=list(opt="optim"))

summary(Model.1a)
coef(Model.1a)

summary(Model.1b)
summary(Model.1c)
Model.1c
```

```{r}
anova.lme(Null.gls,model.1d)

model.1d <- lme(PERFMATH~ESCS+parent_support+gender+student_hindrance+teacher_hindrance+ESCS:student_hindrance+ESCS:teacher_hindrance+parent_support:student_hindrance+parent_support:teacher_hindrance, random=~parent_support+ESCS|CNTSCHID,
              data=qq_phl_merged_complete,control=list(opt="optim"))

summary(model.1d)

model.1e <- lme(PERFMATH~ESCS+parent_support+gender+student_hindrance+teacher_hindrance+ESCS:teacher_hindrance+parent_support:student_hindrance+parent_support:teacher_hindrance, random=~parent_support+ESCS|CNTSCHID,
              data=qq_phl_merged_complete,control=list(opt="optim"))

summary(model.1e)

model.1f <- lme(PERFMATH~ESCS+parent_support+gender+student_hindrance+teacher_hindrance+ESCS:teacher_hindrance+parent_support:student_hindrance, random=~parent_support+ESCS|CNTSCHID,
              data=qq_phl_merged_complete,control=list(opt="optim"))

summary(model.1f)

model.1g <- lme(PERFMATH~ESCS+parent_support+gender+student_hindrance+teacher_hindrance+parent_support:student_hindrance, random=~parent_support+ESCS|CNTSCHID,
              data=qq_phl_merged_complete,control=list(opt="optim"))

summary(model.1g)

VarCorr(Null.Model)
VarCorr(model.1g)
```
```{r}
plot.model.1g.linearity <- plot(resid(model.1g), model.1g$data$PERFMATH)

plot.model.1g.linearity2 <- plot(model.1g$fitted[,2],resid(model.1g) )
plot.model.1g.linearity2 <- plot(model.1g$fitted[,1],resid(model.1g) )


qqnorm(model.1g$resid[,1], main="Level 1 Residuals")
qqline(model.1g$resid[,1])
qqnorm(model.1g$resid[,2], main="Level 2 Residuals")
qqline(model.1g$resid[,2])




plot_model(model.1g, type="diag")

resids_lvl1_sq <- (model.1g$resid[,1])^2
levene.level1resid <- lm(model.1g$resid[,2]~CNTSCHID, data = qq_phl_merged_complete)
anova(levene.level1resid)
```


```{r}
model.1d <- lme(PERFMATH~ESCS+parent_support+gender+student_hindrance+teacher_hindrance+ESCS:student_hindrance+ESCS:teacher_hindrance+ESCS:student_hindrance:teacher_hindrance, random=~parent_support+ESCS|CNTSCHID,
              data=qq_phl_merged_complete,control=list(opt="optim"))

summary(model.1d)
```

lmer
```{r}
library(lme4)
library(lmerTest)
library(ggplot2)
library(interactions)
finalmodel.lmer <- lmer(PERFMATH~ESCS+parent_support+gender+student_hindrance+teacher_hindrance+student_hindrance*parent_support + (parent_support+ESCS|CNTSCHID),data=qq_phl_merged_complete)
summary(finalmodel.lmer)

interact_plot(finalmodel.lmer, pred = parent_support, modx = student_hindrance,  modx.values=c(1,2,3,4), y.label = "PERFMATH", x.label = "index of Parental Support", legend.main="Student Hindrance Levels") +
theme_bw()+
theme(legend.background=element_rect(fill="white",
size=0.5, linetype="solid",color ="black"),
legend.position = c(0.83, 0.21),
axis.title.x = element_text(color="black", size=14),
axis.title.y = element_text(color="black", size=14),
legend.title = element_text(color="black", size=14),
legend.text = element_text(color="black", size=14)
)

```

```{r}
#Bayesian Multilevel Model
options(contrasts = c("contr.sum","contr.poly"))

#Step 1 - Intercept only Model
brms_interceptonly <- brm(PERFMATH ~ 1 + (1|CNTSCHID),
                          data = qq_phl_merged_complete,
                          warmup = 100,
                          iter = 200,
                          chains = 2,
                          cores = 2)
```

```{r}
get_prior(PERFMATH~ESCS+gender+parent_support+student_hindrance+teacher_hindrance+(student_hindrance+teacher_hindrance|CNTSCHID),
          data=qq_phl_merged_complete)

mod1<-brm(PERFMATH~ESCS+gender+parent_support+student_hindrance+teacher_hindrance +parent_support:student_hindrance +(ESCS + parent_support|CNTSCHID),
          data=qq_phl_merged_complete,
          family = gaussian(),
          warmup=1000,
          iter = 10000,
          chains=4,
          cores = 4)

posterior_summary(mod1, pars = c("^b_", "^sd_", "sigma"), probs = c(0.025, 0.975) )

```

```{r}
library(ggplot2)
mod1
mod1 %>% plot(combo = c("hist","trace"), widths = c(1,1.5), theme = theme_bw(base_size=8))
```

```{r}
hyp1 <- hypothesis(mod1, "ESCS = 0")
hyp1
plot(hyp1, theme = theme_bw(base_size = 20))

hyp2 <- hypothesis(mod1, "gender = 0")
hyp2
plot(hyp2, theme = theme_bw(base_size=20))

hyp3 <- hypothesis(mod1, "parent_support = 0")
hyp3
plot(hyp3, theme = theme_bw(base_size=20))

hyp4 <- hypothesis(mod1, "parent_support = 0")
pp_check(mod1,ndraws=200)
```

```{r}

```

